inherit_from: "https://www.goodcop.style/rubocop.yml"

AllCops:
  NewCops: enable
  Exclude:
    - 'excerpts/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 3.1
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

